// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#ifndef FUSE_CTRL_MMAP_HEADERS
#define FUSE_CTRL_MMAP_HEADERS

#include <stdbool.h>
#include <stdint.h>

typedef enum {
    // SW_TEST_UNLOCK_PARTITION
    CPTRA_SS_MANUF_DEBUG_UNLOCK_TOKEN = 0x0000,
    // SECRET_MANUF_PARTITION
    CPTRA_CORE_UDS_SEED = 0x0048,
    // SECRET_PROD_PARTITION_0
    CPTRA_CORE_FIELD_ENTROPY_0 = 0x0098,
    // SECRET_PROD_PARTITION_1
    CPTRA_CORE_FIELD_ENTROPY_1 = 0x00B0,
    // SECRET_PROD_PARTITION_2
    CPTRA_CORE_FIELD_ENTROPY_2 = 0x00C8,
    // SECRET_PROD_PARTITION_3
    CPTRA_CORE_FIELD_ENTROPY_3 = 0x00E0,
    // SW_MANUF_PARTITION
    CPTRA_CORE_ANTI_ROLLBACK_DISABLE = 0x00F8,
    CPTRA_CORE_IDEVID_CERT_IDEVID_ATTR = 0x00FC,
    SOC_SPECIFIC_IDEVID_CERTIFICATE = 0x015C,
    CPTRA_CORE_IDEVID_MANUF_HSM_IDENTIFIER = 0x215C,
    CPTRA_CORE_SOC_STEPPING_ID = 0x216C,
    CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_0 = 0x2170,
    CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_1 = 0x21A0,
    CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_2 = 0x21D0,
    CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_3 = 0x2200,
    CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_4 = 0x2230,
    CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_5 = 0x2260,
    CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_6 = 0x2290,
    CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_7 = 0x22C0,
    // SECRET_LC_TRANSITION_PARTITION
    CPTRA_SS_TEST_UNLOCK_TOKEN_1 = 0x22F8,
    CPTRA_SS_TEST_UNLOCK_TOKEN_2 = 0x2308,
    CPTRA_SS_TEST_UNLOCK_TOKEN_3 = 0x2318,
    CPTRA_SS_TEST_UNLOCK_TOKEN_4 = 0x2328,
    CPTRA_SS_TEST_UNLOCK_TOKEN_5 = 0x2338,
    CPTRA_SS_TEST_UNLOCK_TOKEN_6 = 0x2348,
    CPTRA_SS_TEST_UNLOCK_TOKEN_7 = 0x2358,
    CPTRA_SS_TEST_EXIT_TO_MANUF_TOKEN = 0x2368,
    CPTRA_SS_MANUF_TO_PROD_TOKEN = 0x2378,
    CPTRA_SS_PROD_TO_PROD_END_TOKEN = 0x2388,
    CPTRA_SS_RMA_TOKEN = 0x2398,
    // LIFE_CYCLE
    LC_TRANSITION_CNT = 0x23B0,
    LC_STATE = 0x23E0,
    // VENDOR_HASHES_MANUF_PARTITION
    CPTRA_CORE_VENDOR_PK_HASH_0 = 0x2408,
    CPTRA_CORE_PQC_KEY_TYPE_0 = 0x2438,
    // VENDOR_HASHES_PROD_PARTITION
    CPTRA_SS_OWNER_PK_HASH = 0x2448,
    CPTRA_SS_OWNER_PQC_KEY_TYPE = 0x2478,
    CPTRA_SS_OWNER_PK_HASH_VALID = 0x247C,
    CPTRA_CORE_VENDOR_PK_HASH_1 = 0x2480,
    CPTRA_CORE_PQC_KEY_TYPE_1 = 0x24B0,
    CPTRA_CORE_VENDOR_PK_HASH_2 = 0x24B4,
    CPTRA_CORE_PQC_KEY_TYPE_2 = 0x24E4,
    CPTRA_CORE_VENDOR_PK_HASH_3 = 0x24E8,
    CPTRA_CORE_PQC_KEY_TYPE_3 = 0x2518,
    CPTRA_CORE_VENDOR_PK_HASH_4 = 0x251C,
    CPTRA_CORE_PQC_KEY_TYPE_4 = 0x254C,
    CPTRA_CORE_VENDOR_PK_HASH_5 = 0x2550,
    CPTRA_CORE_PQC_KEY_TYPE_5 = 0x2580,
    CPTRA_CORE_VENDOR_PK_HASH_6 = 0x2584,
    CPTRA_CORE_PQC_KEY_TYPE_6 = 0x25B4,
    CPTRA_CORE_VENDOR_PK_HASH_7 = 0x25B8,
    CPTRA_CORE_PQC_KEY_TYPE_7 = 0x25E8,
    CPTRA_CORE_VENDOR_PK_HASH_8 = 0x25EC,
    CPTRA_CORE_PQC_KEY_TYPE_8 = 0x261C,
    CPTRA_CORE_VENDOR_PK_HASH_9 = 0x2620,
    CPTRA_CORE_PQC_KEY_TYPE_9 = 0x2650,
    CPTRA_CORE_VENDOR_PK_HASH_10 = 0x2654,
    CPTRA_CORE_PQC_KEY_TYPE_10 = 0x2684,
    CPTRA_CORE_VENDOR_PK_HASH_11 = 0x2688,
    CPTRA_CORE_PQC_KEY_TYPE_11 = 0x26B8,
    CPTRA_CORE_VENDOR_PK_HASH_12 = 0x26BC,
    CPTRA_CORE_PQC_KEY_TYPE_12 = 0x26EC,
    CPTRA_CORE_VENDOR_PK_HASH_13 = 0x26F0,
    CPTRA_CORE_PQC_KEY_TYPE_13 = 0x2720,
    CPTRA_CORE_VENDOR_PK_HASH_14 = 0x2724,
    CPTRA_CORE_PQC_KEY_TYPE_14 = 0x2754,
    CPTRA_CORE_VENDOR_PK_HASH_15 = 0x2758,
    CPTRA_CORE_PQC_KEY_TYPE_15 = 0x2788,
    CPTRA_CORE_VENDOR_PK_HASH_VALID = 0x278C,
    // SVN_PARTITION
    CPTRA_CORE_FMC_KEY_MANIFEST_SVN = 0x27A8,
    CPTRA_CORE_RUNTIME_SVN = 0x27AC,
    CPTRA_CORE_SOC_MANIFEST_SVN = 0x27BC,
    CPTRA_CORE_SOC_MANIFEST_MAX_SVN = 0x27CC,
    // VENDOR_TEST_PARTITION
    VENDOR_TEST = 0x27D0,
    // VENDOR_REVOCATIONS_PROD_PARTITION
    CPTRA_SS_OWNER_ECC_REVOCATION = 0x2810,
    CPTRA_SS_OWNER_LMS_REVOCATION = 0x2814,
    CPTRA_SS_OWNER_MLDSA_REVOCATION = 0x2818,
    CPTRA_CORE_ECC_REVOCATION_0 = 0x281C,
    CPTRA_CORE_LMS_REVOCATION_0 = 0x2820,
    CPTRA_CORE_MLDSA_REVOCATION_0 = 0x2824,
    CPTRA_CORE_ECC_REVOCATION_1 = 0x2828,
    CPTRA_CORE_LMS_REVOCATION_1 = 0x282C,
    CPTRA_CORE_MLDSA_REVOCATION_1 = 0x2830,
    CPTRA_CORE_ECC_REVOCATION_2 = 0x2834,
    CPTRA_CORE_LMS_REVOCATION_2 = 0x2838,
    CPTRA_CORE_MLDSA_REVOCATION_2 = 0x283C,
    CPTRA_CORE_ECC_REVOCATION_3 = 0x2840,
    CPTRA_CORE_LMS_REVOCATION_3 = 0x2844,
    CPTRA_CORE_MLDSA_REVOCATION_3 = 0x2848,
    CPTRA_CORE_ECC_REVOCATION_4 = 0x284C,
    CPTRA_CORE_LMS_REVOCATION_4 = 0x2850,
    CPTRA_CORE_MLDSA_REVOCATION_4 = 0x2854,
    CPTRA_CORE_ECC_REVOCATION_5 = 0x2858,
    CPTRA_CORE_LMS_REVOCATION_5 = 0x285C,
    CPTRA_CORE_MLDSA_REVOCATION_5 = 0x2860,
    CPTRA_CORE_ECC_REVOCATION_6 = 0x2864,
    CPTRA_CORE_LMS_REVOCATION_6 = 0x2868,
    CPTRA_CORE_MLDSA_REVOCATION_6 = 0x286C,
    CPTRA_CORE_ECC_REVOCATION_7 = 0x2870,
    CPTRA_CORE_LMS_REVOCATION_7 = 0x2874,
    CPTRA_CORE_MLDSA_REVOCATION_7 = 0x2878,
    CPTRA_CORE_ECC_REVOCATION_8 = 0x287C,
    CPTRA_CORE_LMS_REVOCATION_8 = 0x2880,
    CPTRA_CORE_MLDSA_REVOCATION_8 = 0x2884,
    CPTRA_CORE_ECC_REVOCATION_9 = 0x2888,
    CPTRA_CORE_LMS_REVOCATION_9 = 0x288C,
    CPTRA_CORE_MLDSA_REVOCATION_9 = 0x2890,
    CPTRA_CORE_ECC_REVOCATION_10 = 0x2894,
    CPTRA_CORE_LMS_REVOCATION_10 = 0x2898,
    CPTRA_CORE_MLDSA_REVOCATION_10 = 0x289C,
    CPTRA_CORE_ECC_REVOCATION_11 = 0x28A0,
    CPTRA_CORE_LMS_REVOCATION_11 = 0x28A4,
    CPTRA_CORE_MLDSA_REVOCATION_11 = 0x28A8,
    CPTRA_CORE_ECC_REVOCATION_12 = 0x28AC,
    CPTRA_CORE_LMS_REVOCATION_12 = 0x28B0,
    CPTRA_CORE_MLDSA_REVOCATION_12 = 0x28B4,
    CPTRA_CORE_ECC_REVOCATION_13 = 0x28B8,
    CPTRA_CORE_LMS_REVOCATION_13 = 0x28BC,
    CPTRA_CORE_MLDSA_REVOCATION_13 = 0x28C0,
    CPTRA_CORE_ECC_REVOCATION_14 = 0x28C4,
    CPTRA_CORE_LMS_REVOCATION_14 = 0x28C8,
    CPTRA_CORE_MLDSA_REVOCATION_14 = 0x28CC,
    CPTRA_CORE_ECC_REVOCATION_15 = 0x28D0,
    CPTRA_CORE_LMS_REVOCATION_15 = 0x28D4,
    CPTRA_CORE_MLDSA_REVOCATION_15 = 0x28D8,
    // VENDOR_SECRET_PROD_PARTITION
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_0 = 0x28E8,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_1 = 0x2908,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_2 = 0x2928,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_3 = 0x2948,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_4 = 0x2968,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_5 = 0x2988,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_6 = 0x29A8,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_7 = 0x29C8,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_8 = 0x29E8,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_9 = 0x2A08,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_10 = 0x2A28,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_11 = 0x2A48,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_12 = 0x2A68,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_13 = 0x2A88,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_14 = 0x2AA8,
    CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_15 = 0x2AC8,
    // VENDOR_NON_SECRET_PROD_PARTITION
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_0 = 0x2AF8,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_1 = 0x2B18,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_2 = 0x2B38,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_3 = 0x2B58,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_4 = 0x2B78,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_5 = 0x2B98,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_6 = 0x2BB8,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_7 = 0x2BD8,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_8 = 0x2BF8,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_9 = 0x2C18,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_10 = 0x2C38,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_11 = 0x2C58,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_12 = 0x2C78,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_13 = 0x2C98,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_14 = 0x2CB8,
    CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_15 = 0x2CD8,
    // CPTRA_SS_LOCK_HEK_PROD_0
    CPTRA_SS_LOCK_HEK_PROD_0_RATCHET_SEED = 0x2D00,
    // CSR_PARTITION
    CSR_REGION = 0x2D28
} fuse_k;

typedef enum {
    SW_TEST_UNLOCK_PARTITION,
    SECRET_MANUF_PARTITION,
    SECRET_PROD_PARTITION_0,
    SECRET_PROD_PARTITION_1,
    SECRET_PROD_PARTITION_2,
    SECRET_PROD_PARTITION_3,
    SW_MANUF_PARTITION,
    SECRET_LC_TRANSITION_PARTITION,
    LIFE_CYCLE,
    VENDOR_HASHES_MANUF_PARTITION,
    VENDOR_HASHES_PROD_PARTITION,
    SVN_PARTITION,
    VENDOR_TEST_PARTITION,
    VENDOR_REVOCATIONS_PROD_PARTITION,
    VENDOR_SECRET_PROD_PARTITION,
    VENDOR_NON_SECRET_PROD_PARTITION,
    CPTRA_SS_LOCK_HEK_PROD_0,
    CSR_PARTITION
} partition_k;

typedef struct {
    uint32_t        index;
    uint32_t        address;
    uint32_t        digest_address;
    uint32_t        zer_address;
    uint32_t        variant;
    uint32_t        granularity;
    bool            is_secret;
    bool            hw_digest;
    bool            sw_digest;
    bool            has_ecc;
    uint32_t        lc_phase;
    bool            is_lifecycle;
    // The number of fuses in the partition. Note that this may be
    // larger than the number of fuses explictly specified in the
    // hjson. Any digest or zeroization field is also added to the
    // list.
    uint32_t        num_fuses;
    const uint32_t *fuses;
} partition_t;

#define NUM_PARTITIONS 18

// A map of the NUM_PARTITIONS fuse partitions.
extern const partition_t partitions[];

// Arrays with indices of fuses for each partition.
extern const uint32_t sw_test_unlock_partition_fuses[];
extern const uint32_t secret_manuf_partition_fuses[];
extern const uint32_t secret_prod_partition_0_fuses[];
extern const uint32_t secret_prod_partition_1_fuses[];
extern const uint32_t secret_prod_partition_2_fuses[];
extern const uint32_t secret_prod_partition_3_fuses[];
extern const uint32_t sw_manuf_partition_fuses[];
extern const uint32_t secret_lc_transition_partition_fuses[];
extern const uint32_t life_cycle_fuses[];
extern const uint32_t vendor_hashes_manuf_partition_fuses[];
extern const uint32_t vendor_hashes_prod_partition_fuses[];
extern const uint32_t svn_partition_fuses[];
extern const uint32_t vendor_test_partition_fuses[];
extern const uint32_t vendor_revocations_prod_partition_fuses[];
extern const uint32_t vendor_secret_prod_partition_fuses[];
extern const uint32_t vendor_non_secret_prod_partition_fuses[];
extern const uint32_t cptra_ss_lock_hek_prod_0_fuses[];
extern const uint32_t csr_partition_fuses[];

#endif // FUSE_CTRL_MMAP_HEADERS
